### PR TITLE
Added directory exclusions to Haiku9's S3 sync process.  

### PR DESCRIPTION
**Pull request by freeformflow**
Paths are specified in h9.yaml.  All path descendants are excluded.

### CODE REVIEW

**Comment by jessefrye** [comment]
LGTM

To test I ran a local version of Haiku9 and it didn't delete the blurbs folder in S3 which is the expected behavior 

h9.yaml file had this addition:

```
exclusions:
  - "blurbs"
```

**Comment by dyoder** [comment]
Is for #104? If not, why is it necessary?

If it's for #104, the idea was to exclude things from the survey/build not from sync.

**Comment by jessefrye** [comment]
@dyoder not for #104  

If you make changes to something server side (like meta tags to alter a template) this keeps a local push from blitzing that change during sync

**Comment by dyoder** [comment]
Ah, I see.

**Pull request merged**
